version: "3"
services:
  rockpaperscissors-sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: rockpaperscissors-sql
    environment:
      MSSQL_SA_PASSWORD: ""
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
  rockpaperscissors-server:
    build:
      context: .
      dockerfile: Dockerfile-Server
    container_name: rockpaperscissors-server
    environment:
      "ConnectionStrings__DefaultConnection": ""
    ports:
      - "80:80"
    depends_on:
      - rockpaperscissors-sql