name: Create new hack with OpenAI

on:
  workflow_dispatch:
    inputs:
      hackName:
        description: The name of the hack you want to create
        required: true
        default: YetAnotherHack
      description:
        description: A description of the hack
        required: true
        default: "Create a WhatTheHack for creating a WhatTheHack."
      keywords:
        description: A comma separated list of keywords (these will be used to guide the AI to generate challenges)
        required: true
        default: "WhatTheHack, GitHub, Actions, AI"
      numberOfChallenges:
        description: The number of challenges you want (note that it is better to auto-generate more challenges than you think you will need, you can always delete the files later)
        required: true
        default: "3"
jobs:
  createNewWhatTheHackTemplate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      BRANCH_NAME: xxx-${{ github.event.inputs.hackName }}
    steps:
      - uses: actions/checkout@v3
      - name: Create new branch
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git checkout -b ${{ env.BRANCH_NAME }}
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ github.workspace }}/.github/workflows/create-wth-template-openai/requirements.txt
      - name: Generate WhatTheHack template stubs
        run: python ${{ github.workspace }}/.github/workflows/create-wth-template-openai/create-wth-template-openai.py --path_to_hack ${{ github.workspace }} --number_of_challenges "${{ github.event.inputs.numberOfChallenges}}" --name_of_hack "${{ github.event.inputs.hackName }}" --description_of_hack "${{ github.event.inputs.description }}" --keywords "${{ github.event.inputs.keywords }}" --openai_endpoint_uri "${{ secrets.OPENAI_ENDPOINT_URI }}" --openai_api_key "${{ secrets.OPENAI_API_KEY }}" --openai_gpt_model_name "${{ vars.OPENAI_GPT_MODEL_NAME }}" --openai_embedding_model_name "${{ vars.OPENAI_EMBEDDING_MODEL_NAME }}" --remove_existing_directory --verbose
      - name: Push branch
        run: |
          git add *
          git commit -m 'Created WhatTheHack template stub'
          git push -u origin ${{ env.BRANCH_NAME }}
