name: Create a release for a WhatTheHack hackathon

on:
  workflow_call:
    inputs:
      hackathonNames:
        description: "The name of the hackathon to create a release for"
        required: true
        type: string
      pathToStudentResources:
        description: "The path to the Student Resources directory."
        required: true
        type: string
      branchName:
        description: "The name of the branch to create the release from."
        required: true
        type: string

jobs:
  package:
    strategy:
      matrix:
        hackathonName: ${{ fromJSON(inputs.hackathonNames) }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: echo "TAG=${{ matrix.hackathonName }}" >> $GITHUB_ENV
      - run: |
          cd ${{ matrix.hackathonName }}/${{ inputs.pathToStudentResources }}
          zip -r ${{ env.RESOURCES_FILENAME }} *

          gh release delete ${{ env.TAG }} --yes 2>/dev/null 

          gh release create ${{ env.TAG }}  \
            --title "Student Resources for ${{ matrix.hackathonName }}" \
            --notes "Student Resources for ${{ matrix.hackathonName }}" \
            --target ${{ inputs.branchName }}

          gh release upload ${{ env.TAG }} ${{ env.RESOURCES_FILENAME }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RESOURCES_FILENAME: Resources
