name: Create a release for a WhatTheHack hackathon

on:
  workflow_dispatch:
    inputs:
      hackathonName:
        description: "The name of the hackathon to create a release for"
        required: true
        default: "001-IntroToKubernetes"
      pathToStudentResources:
        description: "The path to the Student Resources directory."
        required: true
        default: "Student/Resources"
      branchName:
        description: "The name of the branch to create the release from."
        required: true
        default: "master"

jobs:
  package:
    uses: ./.github/workflows/create-wth-release.yml
    with:
      hackathonName: ${{ inputs.hackathonName }}
      pathToStudentResources: ${{ inputs.pathToStudentResources }}
      branchName: ${{ inputs.branchName }}

