name: Create a release for a WhatTheHack hackathon

on:
  workflow_dispatch:
    inputs:
      hackathonName:
        description: "The name of the hackathon to create a release for"
        required: true
        default: "001-IntroToKubernetes"
      pathToStudentResources:
        description: "The path to the Student Resources directory."
        required: true
        default: "Student/Resources"
      branchName:
        description: "The name of the branch to create the release from."
        required: true
        default: "master"
  push:
    branches:
      - master 

env:
  HACKATHON_NAME: ${{ github.event.inputs.hackathonName != '001-IntroToKubernetes' && github.event.inputs.hackathonName || '001-IntroToKubernetes'}}
  PATH_TO_STUDENT_RESOURCES: ${{ github.event.inputs.pathToStudentResources != 'Student/Resources' && github.event.inputs.pathToStudentResources || 'Student/Resources'}}
  BRANCH_NAME: ${{ github.event.inputs.branchName != 'master' && github.event.inputs.branchName || 'master'}}

jobs:
  package:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: echo "TAG=${{ env.HACKATHON_NAME }}" >> $GITHUB_ENV
      - run: |
          cd ${{ env.HACKATHON_NAME }}/${{ env.PATH_TO_STUDENT_RESOURCES }}
          zip -r ${{ env.RESOURCES_FILENAME }} *

          gh release create ${{ env.TAG }}  \
            --title "Student Resources for ${{ env.HACKATHON_NAME }}" \
            --notes "Student Resources for ${{ env.HACKATHON_NAME }}" \
            --target ${{ env.BRANCH_NAME }}

          gh release upload ${{ env.TAG }} ${{ env.RESOURCES_FILENAME }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RESOURCES_FILENAME: Resources
