name: Create a repo for a WhatTheHack hackathon

on:
  workflow_dispatch:
    inputs:
      hackathonName:
        description: "The name of the hackathon to create a release for"
        required: true
        default: "001-IntroToKubernetes"
      pathToStudentResources:
        description: "The path to the Student Resources directory."
        required: true
        default: "Student/Resources"
      branchName:
        description: "The name of the branch to create the release from."
        required: true
        default: "master"

jobs:
  create-repo:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: |
          git checkout ${{ inputs.branchName }}

          cd ${{ inputs.hackathonName }}/${{ inputs.pathToStudentResources }}

          git config --global init.defaultBranch main

          git init

          echo $ORG_ADMIN_TOKEN > ~/ORG_ADMIN_TOKEN.txt

          gh auth login --with-token < ~/ORG_ADMIN_TOKEN.txt

          gh repo create ${{ inputs.hackathonName }} --public --source=. --remote=${{ inputs.hackathonName }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORG_ADMIN_TOKEN: ${{ secrets.ORG_ADMIN_TOKEN }}