name: Spell Check

on:
  pull_request:
    types:
      - opened
    branches: [master]
    paths:
      - "**.md"

  workflow_dispatch:

jobs:
  spell-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            **/*.md

      - uses: jordanbean-msft/wth-spell-check-action@v0.0.21
        name: WTH Spell Check
        with:
          spell_check_yaml_path: .github/workflows/spell-check/spellcheck.yml
          markdown_base_path: .
          changed_files: ${{ steps.changed-files.outputs.all_changed_files }}
